### ISSUE TITLE
Installation of Nefi2 on Mac stuck

### ISSUE THREAD

**Issue by 05dirnbe** [tastyminerals/NEFI2#1]
Hi there,

i managed with some trial and error to install all but one of the listed dependecies of Nefi2. The following imports work for my **python 3.5.1**:

- numpy: **1.10.4**
- networkx: **1.11**
- opencv3: **3.1.0**
- demjson: **2.2.4**
- PyQt5: **5.5.1**

I still failed to install the thinning module. In the docs it says you download it from somewher, however i didnt find a working link to the download.

Please fix the link in the documentation and tell me how to get thinning installed.

best, m

**Comment by tastyminerals** [comment]
thinning module for python3 is in my github repo: https://github.com/tastyminerals/thinning_py3.git
```
git clone https://github.com/tastyminerals/thinning_py3.git
cd thinning_py3
sudo python3 setup.py install
```

**Comment by Rapdrei** [comment]
Michael can you try to create a python wheel on Mac? I dont know if we can make a generic wheel for every distro and python version. This would only be possible if thinning setup doesnt use any binary resources.
Here is a link to wheel: http://pythonwheels.com/
Sorry that we are not much of a help for mac. Its difficult to build a package since we dont have acess to a maching.

**Comment by 05dirnbe** [comment]
Right now, i have no capacities to look into that. I need to work towards finishing a paper. Dont worry too much about it right now.
